version: '3.9'
services:
  db:
    image: postgres:15
    container_name: smart_customer_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 8254
      POSTGRES_DB: customer_analysis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init/:/docker-entrypoint-initdb.d/

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: smart_customer_web
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://myuser:8254@db/customer_analysis
    command: ["python", "run.py", "serve"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  pgdata:
